# Generated by Django 5.2 on 2025-05-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='sintomas',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='sintomas',
            field=models.ManyToManyField(related_name='diagnosticos', to='consultas.sintomas'),
        ),
    ]
